// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNQjFV2Zk6EF_3zynmexqx0H-juROnUE',
    appId: '1:604468576874:web:49de63b4a2a42955724013',
    messagingSenderId: '604468576874',
    projectId: 'news-app-13b1f',
    authDomain: 'news-app-13b1f.firebaseapp.com',
    storageBucket: 'news-app-13b1f.firebasestorage.app',
    measurementId: 'G-QW62N66KWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB74PWY-B9rJCKvCUvKx1CpDMq9UzCZGaU',
    appId: '1:604468576874:android:3e8462024caa0c72724013',
    messagingSenderId: '604468576874',
    projectId: 'news-app-13b1f',
    storageBucket: 'news-app-13b1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltgAsj_6NUvzfQjSB8FB4nUsg_wjIUs0',
    appId: '1:604468576874:ios:6e9dcb84c6664ebc724013',
    messagingSenderId: '604468576874',
    projectId: 'news-app-13b1f',
    storageBucket: 'news-app-13b1f.firebasestorage.app',
    iosBundleId: 'com.example.newsAppWithApi',
  );
}
